<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0-android;net10.0-ios;net10.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.19041.0</TargetFrameworks>

		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<RestoreSources>$(RestoreSources);C:\Users\azert\source\repos\projectFrameCut.PluginTemplate\projectFrameCut.PluginPackager.MSBuild\bin\Release</RestoreSources>

		<GeneratePluginInfoSource>false</GeneratePluginInfoSource>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<!--You must set all these properties below, except PluginAssetPath.-->

		<!--
				This'll be the ID of the plugin. 
				It muse equals to the full name of your implementation of IPluginBase, and SHOULD NOT starts with 'projectFrameCut'.
		-->
		<PackageId>nobody.MyExamplePlugin_AppParticalPart</PackageId>
		<PluginIDOverride>nobody.MyExamplePlugin</PluginIDOverride>
		<Version>42.42.42.42</Version>
		<PluginSignFilePath>D:\code\playground\projectFrameCut\key.json</PluginSignFilePath>
		<PackageProjectUrl>https://example.com/1</PackageProjectUrl>

		<!--These attributes define metadata for the plugin in the neutral language. To define the metadata for other languages, use the LocalizationProvider.-->

		<Title>Example plugin</Title>
		<Authors>none</Authors>
		<Description>desc</Description>

		<!--The path to the plugin's assets. Note this is optional.-->
		<PluginAssetPath>D:\code\playground\projectFrameCut\plugin\asset</PluginAssetPath>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
		<Reference Include="..\PluginBaseAssembly\projectFrameCut.Render.RenderAPIBase.dll" />
		<Reference Include="..\PluginBaseAssembly\projectFrameCut.ApplicationAPIBase.dll" />
    <Reference Include="..\PluginBaseAssembly\projectFrameCut.Shared.dll" />
    <PackageReference Include="projectFrameCut.PluginPackager.MSBuild" Version="2.0.0" />		
		
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\projectFrameCut.PluginTemplate\projectFrameCut.PluginTemplate.csproj" />
	</ItemGroup>


</Project>
